### ISSUE TITLE
Rx560 4G 24mh or 4mh ?

### ISSUE THREAD

**Issue by sebbonnaire** [Lolliedieb/lolMiner-releases#243]
Hi everyone 
I am experiencing a strange behavior since “super zombie mode” (or something else which seams to be related to szm to me) :
- my estimated hash rate raised to 24+ (with r560 4g overclocked to 985-2225. My hash rate was 12,7 before szm)
- my average hash rate is now only around 4mh (is was around 12,7 before szm)

for information my pc is not the newest : a Xeon 1240 in an HP Elite 8300, with 12G ddr3 ram. I do not have any error nor warnings in logs either. 

I first couldn’t understand how my hash rate could be so high... and after a few minutes I regretted my 12mh.

Can you tell me if I’ve done something wrong ? Or if my graphics card is dead maybe ?

Note : lowering the OC values give me the same kind of gap between estimated hash rate et average hash rate...

**Comment by Titomir** [comment]
560 4Gb newer gives more than 15mh/s. Anyway give 2100 by memory. And after start miner don't watch on hashrate in about 5 minutes. Tuning is look for a best zombie mode. When tune completed - u can see your real hashrate.

**Comment by sebbonnaire** [comment]
Hi
i’m Looking the hash rate after a long period of time(1 hour average) taking the figures from the hiveos portal also (which takes the average per hour).
On my PC (I have only one at this time), I have tried to reinstall a fresh hiveos, and also swapped my rx560 by an rx560D. I still have after thoses changes a huge hash rate seen by lolminer (more than 20mh), but the real hash rate is still around 4mh.

any advices ?

**Comment by sebbonnaire** [comment]
It seams to be solved in the next version 

I'll make a try ASAP

**Comment by sebbonnaire** [comment]
Solved by 1.24a

**Comment by rst108** [comment]
> Solved by 1.24a

how many MH/s?

**Comment by sebbonnaire** [comment]
> > Solved by 1.24a
> 
> 
> 
> how many MH/s?
> 
> 

Now it is around 12mhs by epoch 399

**Comment by rst108** [comment]
> > > Solved by 1.24a
> > 
> > 
> > how many MH/s?
> 
> Now it is around 12mhs by epoch 399

Im still getting 21++ with rx 580 4gb using linux hiveos.
Already order rx 560 we'll check if its only 12mhs.
