### ISSUE TITLE
error when allocating memory for the DAG. Disabling card

### ISSUE THREAD

**Issue by danteshort** [Lolliedieb/lolMiner-releases#429]
hi, i have this error and i don't know how to fix it i have a 1050 ti graphics card
![asdasdas](https://user-images.githubusercontent.com/82298487/114290398-dd433900-9a55-11eb-9b14-4199c383f8c4.png)

**Comment by androiddisk** [comment]
me too 
GPU:980M
GPU 0: error when allocating memory for the DAG. Disabling card.

**Comment by jutonlahyene** [comment]
Same with me, also with 1060 card

**Comment by fanyadan** [comment]
Same issue here,
![image](https://user-images.githubusercontent.com/947021/114310235-c287c780-9b1c-11eb-8063-57d00bcb627e.png)

**Comment by Lolliedieb** [comment]
Not a bug. Ethash now needs more then 4GByte of memory. Mining ETC will work.

**Comment by romantra** [comment]
I was minning good with my cards (nvidia quadro p2200 5gb memory each) but suddenly I got the error message "GPU 0: error when allocating memory for the DAG. Disabling card" any idea why I got this error and suddenly can't mine eth and only etc?

![image](https://user-images.githubusercontent.com/48365913/114775274-bd9e6000-9d36-11eb-93b5-8033f23d19c1.png)

![image](https://user-images.githubusercontent.com/48365913/114775353-d27af380-9d36-11eb-8d90-458b502cda99.jpeg)

**Comment by cryp-tog** [comment]
https://minerstat.com/dag-size-calculator says Epoch 407 was 4.180Gb, Epoch 408 is now 4.188.  And it *just* happened.  Not sure your cards are big enough anymore.  Maybe try reserving more system space (--keepfree arg (=5))?  Can you back off any overclocking?

**Comment by romantra** [comment]
> https://minerstat.com/dag-size-calculator says Epoch 407 was 4.180Gb, Epoch 408 is now 4.188.  And it *just* happened.  Not sure your cards are big enough anymore.  Maybe try reserving more system space (--keepfree arg (=5))?  Can you back off any overclocking?

My cards are 5gb each as you can see here:

![image](https://user-images.githubusercontent.com/48365913/114779982-669b8980-9d3c-11eb-9ff1-bb3a9db1bb07.jpeg)

Can you explain me how to use the --keep free option with an example please?

**Comment by Lolliedieb** [comment]
Keepfree does not apply here.
Not sure why this happens so early - does one of them do the GPU output in parallel?
At the moment we also occupy space for stuff like light cache and so ... doing some work here will maybe give us ~16 more epochs ... I will try

**Comment by romantra** [comment]
This means that you will update the app? Because I can mine with trex and Phoenix ethereum but with lolminer I get the DAG error message I mentioned...🙂 

> Keepfree does not apply here.
> 
> Not sure why this happens so early - does one of them do the GPU output in parallel?
> 
> At the moment we also occupy space for stuff like light cache and so ... doing some work here will maybe give us ~16 more epochs ... I will try

**Comment by Attackpug1** [comment]
Am having the same problem. Using a GTX965m

**Comment by Lolliedieb** [comment]
The 965m got only 4G memory, which is not enough for mining Ethereum. Try
ETC or an other coin.

Wrt the 5G cards: yes, I will try to fix this.

Attackpug1 ***@***.***> schrieb am Sa., 17. Apr. 2021, 03:46:

**Comment by nottheotherside** [comment]
> The 965m got only 4G memory, which is not enough for mining Ethereum. Try
ETC or an other coin.

Well, lolMiner has a separate predefined batch file for 4GB **ETH** mining
![image](https://user-images.githubusercontent.com/12183499/115107609-ad31f380-9f89-11eb-97b3-05e1ca8ac1f6.png)
When you open this file it shows `--4g-alloc-size 4024` which means it should be working with 4GB cards too, given that a 4GB card has 4096MB, allocating 4024MB should be fine, right?
I have the same problem too (using GTX1650 4GB, lolMiner v1.26).

**Comment by Lolliedieb** [comment]
Indeed, this file exists because of the Zombie mode that allows under
certain circumstances to continue mining. It was mostly made for 4G amd
cards. For Nvidias this sadly never worked at reasonable speed, because the
driver behaves differently then amds when doing card to host communication.
Therefore it was not implemented for the cuda back end.

Am Sa., 17. Apr. 2021 um 11:06 Uhr schrieb nottheotherside <
***@***.***>:

**Comment by E-T-II** [comment]
> Not a bug. Ethash now needs more then 4GByte of memory. Mining ETC will work.

ETC does not work either. Of course, I'm using an old NVIDIA GeForce GTX 1060 3GB

**Comment by gionn** [comment]
```
lolMiner.exe --algo ETHASH --pool mypool --user myuser --worker worker--enablezilcache
```

```
Device 0:
    Name:    NVIDIA GeForce GTX 1060 6GB
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  6144 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)
```

```
Start Mining...
GPU 0: error when allocating memory for the DAG. Disabling card.
```

Got this after updating lolminer to 1.26, while 1.21 is working fine.

**Comment by jssmomo** [comment]
Same issue happens for a 1080:
Device 0:
    Name:    GeForce GTX 1080
    Address: 1:0
    Vendor:  NVIDIA Corporation
    Drivers: Cuda, OpenCL
    Memory:  8192 MByte
    Active:  true (Selected Algorithm: ETHash Cuda)

Connecting to pool...
Connected to eth-us-west1.nanopool.org:9999  (TLS disabled)
Set Ethash stratum mode: Ethereum Proxy
Authorized worker: xxx.lolMinerWorkerxxx
New job received: 0xab2d55 Epoch: 413 Target: 000000006df37f67
Start Mining...
New job received: 0xab2d55 Epoch: 413 Target: 000000006df37f67
New job received: 0xcac816 Epoch: 413 Target: 000000006df37f67
**GPU 0: error when allocating memory or building DAG. Disabling card.**

**Comment by kizoChange** [comment]
![image](https://user-images.githubusercontent.com/59013949/117619937-7921ab00-b1a2-11eb-9e24-a55a39bb3692.png)
I also have such a mistake, do you know how to solve it

**Comment by romantra** [comment]
> hi, i have this error and i don't know how to fix it i have a 1050 ti graphics card
> 
> ![asdasdas](https://user-images.githubusercontent.com/82298487/114290398-dd433900-9a55-11eb-9b14-4199c383f8c4.png)
> 
> 
> 
> 
> 
> 

Use an older version. That worked for me

**Comment by Lolliedieb** [comment]
Or use a newer ^^ That issues was addressed with 1.28a :)

romantra ***@***.***> schrieb am Mo., 10. Mai 2021, 15:22:

**Comment by elasticdotventures** [comment]
If anybody figures out how to run lolminer for ETHASH on a 4gb Ti1050 plz lmk.

**Comment by sighclone** [comment]
> > Not a bug. Ethash now needs more then 4GByte of memory. Mining ETC will work.
> 
> ETC does not work either. I'm using an old NVIDIA GeForce GTX 1060 3GB

@E-T-II ETCHASH works with 4GB cards, not 3GB

**Comment by Lolliedieb** [comment]
Actually we had ETCHash working on 1060 3G with 1.28a - at the moment ETC
mining needs ~2.7G.

Abhinav Sadhu ***@***.***> schrieb am Di., 11. Mai 2021,
06:37:

**Comment by liquidrone** [comment]
Hi, i'm currently running a GEForce GTX 1650, and my computer is showing I have 8.00 GB of RAM. I'm still getting the error of the original poster and I'm at a loss on how to fix it.

**Comment by sighclone** [comment]
> Hi, i'm currently running a GEForce GTX 1650, and my computer is showing I have 8.00 GB of RAM. I'm still getting the error of the original poster and I'm at a loss on how to fix it.

You need 4GB of VRAM irrespective of amount of RAM. The  GTX1650 has only 4GB of VRAM.

**Comment by afontan** [comment]
Still getting the error with GTX1660 6GB

**Comment by Lukasko84** [comment]
![image](https://user-images.githubusercontent.com/84182754/118264095-79c68400-b4b7-11eb-8690-bfeae522353e.png)
Hi all, i have a same problem... 4 months was mining without any issue, but yesterday process was stopped... i have 2070 rtx, 8GB ram..i dont understand this.  I try any soft for mining, but i got still same problem.

**Comment by Lolliedieb** [comment]
Please update to current 1.28a - it addresses the issue

Lukasko84 ***@***.***> schrieb am Fr., 14. Mai 2021, 13:25:

**Comment by McMokka** [comment]
@Lolliedieb I just ran into the same problem, was working with 1.21 before, until I got "allocation of dag failed with error memory object allocation failure" out of the blue
updated to 1.28a, getting "error when allocating memore or building dag. disabling card." now.

![768b76c0db42d1d8b5922b4fb7e9d256](https://user-images.githubusercontent.com/84391580/118657552-e14c3e80-b7eb-11eb-8f3a-925ef3fccf20.png)


any way to fix this?

**Comment by romantra** [comment]
> @Lolliedieb I just ran into the same problem, was working with 1.21 before, until I got "allocation of dag failed with error memory object allocation failure" out of the blue
> 
> updated to 1.28a, getting "error when allocating memore or building dag. disabling card." now.
> 
> 
> 
> ![768b76c0db42d1d8b5922b4fb7e9d256](https://user-images.githubusercontent.com/84391580/118657552-e14c3e80-b7eb-11eb-8f3a-925ef3fccf20.png)
> 
> 
> 
> 
> 
> any way to fix this?

Downgrade

**Comment by McMokka** [comment]
> > @Lolliedieb I just ran into the same problem, was working with 1.21 before, until I got "allocation of dag failed with error memory object allocation failure" out of the blue
> > updated to 1.28a, getting "error when allocating memore or building dag. disabling card." now.
> > ![768b76c0db42d1d8b5922b4fb7e9d256](https://user-images.githubusercontent.com/84391580/118657552-e14c3e80-b7eb-11eb-8f3a-925ef3fccf20.png)
> > any way to fix this?
> 
> Downgrade

even further than 1.21? I get 2 different errors for each version, and 1.21 was working up until now.

**Comment by Lolliedieb** [comment]
Ok, this is strange.

Can you guys please share your exact driver version with me (and if its Windows or Linux), so I can try reproducing it?

**Comment by Lolliedieb** [comment]
Also let me know if screen is connected to the cards please.

**Comment by McMokka** [comment]
I just updated the drivers to the most recent one, that nvidia released today, apparently. It fixed things for both versions.
running Windows and with screens connected. Thanks for the quick reply!

**Comment by afontan** [comment]
Same to me, updated nvidia driver and works perfect

**Comment by ThisIsSajid1** [comment]
I updated nvidia driver but still getting the error. Can someone please help?

**Comment by ThisIsSajid1** [comment]
> Same to me, updated nvidia driver and works perfect


WIndows or Linux?

**Comment by ThisIsSajid1** [comment]
> > I updated Nvidia driver but still getting the error. Can someone please help?
> > 1.29 is for Linux right?
> > I need for windows 10 (Tried 1.28a, not working DAG file error)
> 
> My troubleshooting(Windows, RTX 3070):
> -do I have enough vram? (8GB, so yes)
> -update release of lolminer
> -install new drivers (466.47)
> -restart PC

Okay
I have a 1050ti (4 GB) card 
I know its very unlikely to mine ETH with this card
Should I give up completely?

**Comment by Gretschi** [comment]
I have the same problem on 2 cards. Got 8x Asus RTX3080 TUF in total. I reinstalled everything and updated the driver. As soon as I plug in the 7th. card one card i not working. and with 8 cards two are not working anymore

**Comment by RunOrDrink** [comment]
For those with multiple gpus with more than 6gb for each, try to increase your page file to at least 32gb, restart and try again with all gpus connected.

**Comment by kiranp88** [comment]
I tested my GTX 1060 6GB card with version 1.28 mining  ETH only and worked fine, however dual mining ETH + ZIL threw up the same error as the original post. 

Same error goes for versions 1.26, 1.25, BUT it works just fine with 1.21.

My GTX1060 is also connected to the my monitor with a 60000 page file. 

@Lolliedieb , seems as though the adoption of cuda broke something (?) could a fix be implemented in the next version please? Thank you.

**Comment by LustShot** [comment]
I fixed mine, I had the same issue on a 1660ti. I opened task manager and noticed that there was 2 miners open at the same time but i didn't noticed the second one, I closed both and then opened up the one I use normally and everything works fine now

**Comment by jessewhocodes** [comment]
Same issue as others; 6G GeForce GTX 1660 running windows 10 - Driver 27.21.14 5751. Has been working fine for weeks-literally stopped working a few hours ago. Using lolminer 1.28a and get the same error on builds as far back as 1.19. 
![lol-miner](https://user-images.githubusercontent.com/82328829/122627981-48764080-d081-11eb-8335-73cdd313fbd9.JPG)

**Comment by Lolliedieb** [comment]
Try to use
--mode s
in 1.28 - this might help here

jessewhocodes ***@***.***> schrieb am Sa., 19. Juni 2021,
04:05:

**Comment by DrumMajorThrawn** [comment]
> For those with multiple gpus with more than 6gb for each, try to increase your page file to at least 32gb, restart and try again with all gpus connected.

This 100% worked for me running 4 1660 supers

**Comment by mdnafil** [comment]
**Can you please tell me on how to resolve this?**
![Mining (2)](https://user-images.githubusercontent.com/63558220/129080458-7cec56f3-9d26-421a-813f-3009238bfb50.jpg)
![Mining1_LI (3)](https://user-images.githubusercontent.com/63558220/129080465-ea1d2796-a560-4153-bba2-21e0cd0ee6b6.jpg)

**Comment by federalarty** [comment]
I have the same problem, the Lol Miner miner gives an error when I run the three GPU cards at the same time, but when I run on another ETC network the cards work normal.
2x GTX 1070 board
1x GTX 1060 board

**Comment by jgonzis** [comment]
Zombie mode is not working in Windows any more with 4Gb.

**Comment by PEIPEI0924** [comment]
![image](https://user-images.githubusercontent.com/125209033/218325637-288f451c-3970-4969-9e0c-0368ec86e411.png)
what should i do HELP ME~

**Comment by PEIPEI0924** [comment]
> > ![圖片](https://user-images.githubusercontent.com/125209033/218325637-288f451c-3970-4969-9e0c-0368ec86e411.png)我該怎麼辦幫幫我~
> 
> 我看不出有什麼問題


So is this normal operation?

**Comment by JK15246** [comment]
![Snipaste_2024-12-13_22-23-13](https://github.com/user-attachments/assets/3fc3334a-142b-41a1-8b49-abca74ea595e)
how to solve about the speed problem ?
thank you .
